import type { Metadata } from 'next';
import './globals.css';
import { Manrope } from 'next/font/google';

import { ConvexAuthNextjsServerProvider } from '@convex-dev/auth/nextjs/server';
import { ConvexClientProvider } from '@/components/convex-client-provider';

const manrope = Manrope({
  subsets: ['latin'], // Pilih subset sesuai kebutuhan
  weight: ['500', '800'], // Pilih berat font yang diinginkan
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en">
        <body className={manrope.className}>
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
